### ISSUE TITLE
libkvmi v6

### ISSUE THREAD

**Issue by Wenzel** [bitdefender/libkvmi#1]
Hi,

would it be possible to have a branch with libkvmi for kvmi-v6 ?
this is the version that will be included in libvmi:
https://github.com/libvmi/libvmi/pull/844

I'm writing the PR to use your repo:
https://github.com/KVM-VMI/libvmi/pull/32/files

thanks !

**Comment by adlazar** [comment]
@Wenzel , I've used the files from https://github.com/adlazar/kvm/tree/kvmi-v6 for https://github.com/bitdefender/libkvmi/pull/4 . I hope it works.
